-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql/new)

-- 1. Create the server_status table
CREATE TABLE server_status (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tunnel_url TEXT DEFAULT '',
  auth_token TEXT DEFAULT '',
  host_device TEXT DEFAULT '',
  status TEXT DEFAULT 'off' CHECK (status IN ('on', 'off', 'starting', 'stopping')),
  player_count INTEGER DEFAULT 0,
  recent_logs TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert the initial row (the dashboard will read this one row)
INSERT INTO server_status (tunnel_url, auth_token, host_device, status)
VALUES ('', '', 'Android (Termux)', 'off');

-- 2. Enable Row Level Security
ALTER TABLE server_status ENABLE ROW LEVEL SECURITY;

-- 3. Allow any authenticated user to read/write server_status
CREATE POLICY "authenticated users can read"
  ON server_status FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "authenticated users can insert"
  ON server_status FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "authenticated users can update"
  ON server_status FOR UPDATE
  USING (auth.role() = 'authenticated');

-- 4. Enable Realtime (for live dashboard updates)
-- Go to: https://supabase.com/dashboard/project/_/database/replication
-- Add the "server_status" table to the "supabase_realtime" publication
-- Or run:
-- BEGIN;
--   DROP publication IF EXISTS supabase_realtime;
--   CREATE publication supabase_realtime;
-- ALTER publication supabase_realtime ADD TABLE server_status;
-- COMMIT;
